version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: pereval_postgres
    environment:
      POSTGRES_DB: pereval_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI приложение
  app:
    build: .
    container_name: pereval_app
    environment:
      FSTR_DB_HOST: postgres
      FSTR_DB_PORT: 5432
      FSTR_DB_LOGIN: postgres
      FSTR_DB_PASS: password
      FSTR_DB_NAME: pereval_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
